### ISSUE TITLE
Can't install in MacOS X with node 0.10.40

### ISSUE THREAD

**Issue by mkopinsky** [stephenwvickers/node-raw-socket#12]
As of raw-socket version 1.4, `npm install` is failing as follows. If I `npm install raw-socket@1.3.3` it works fine.

```
$ npm install raw-socket
-
> raw-socket@1.4.0 install /Users/kopinsky/tmp/raw-socket-test/node_modules/raw-socket
> node-gyp rebuild

  CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc:662:21: error: expected ';' after expression
                String::Utf8String address (args[3]);
                                  ^
                                  ;
../src/raw.cc:662:11: error: no member named 'Utf8String' in 'v8::String'
                String::Utf8String address (args[3]);
                ~~~~~~~~^
../src/raw.cc:662:31: error: use of undeclared identifier 'args'
                String::Utf8String address (args[3]);
                                            ^
../src/raw.cc:663:44: error: use of undeclared identifier 'address'
                struct sockaddr_in6 addr = uv_ip6_addr (*address, 0);
                                                         ^
../src/raw.cc:673:21: error: expected ';' after expression
                String::Utf8String address (info[3]);
                                  ^
                                  ;
../src/raw.cc:673:11: error: no member named 'Utf8String' in 'v8::String'
                String::Utf8String address (info[3]);
                ~~~~~~~~^
../src/raw.cc:673:22: error: use of undeclared identifier 'address'
                String::Utf8String address (info[3]);
                                   ^
../src/raw.cc:674:43: error: use of undeclared identifier 'address'
                struct sockaddr_in addr = uv_ip4_addr (*address, 0);
                                                        ^
8 errors generated.
make: *** [Release/obj.target/raw/src/raw.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kopinsky/tmp/raw-socket-test/node_modules/raw-socket
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "raw-socket"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kopinsky/tmp/raw-socket-test/npm-debug.log
```

**Comment by stephenwvickers** [comment]
Hi,

The latest version of raw-socket is tested on 0.12.x and onwards.

Please use a more recent version of node.js, or an earlier version of raw-socket.

Steve
