### ISSUE TITLE
Error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by d30jeff** [stephenwvickers/node-raw-socket#27]
I'm getting 

```
Error: Resource temporarily unavailable
    at Error (native)
    at Socket.onRecvReady (/root/openwrt-statsmon/node_modules/raw-socket/index.js:86:13)
    at emitNone (events.js:67:13)
    at SocketWrap.emit (events.js:166:7)
```

After leaving the app run for some time.

I'm using this with [node-net-ping](https://github.com/stephenwvickers/node-net-ping)

and I've added 

```
this.socket = raw.createSocket(options);
this.socket.setOption(
  raw.SocketLevel.SOL_SOCKET,
  raw.SocketOption.SO_BINDTODEVICE,
  new Buffer(this.iface),
  this.iface.length
)
```

**Comment by stephenwvickers** [comment]
After finishing with a ping session you should ensure you close the session, or re-use it again next time.

**Comment by d30jeff** [comment]
I tried closing the session like this:
```
var session = _netPing.createSession({
  iface: iface,
  timeout: 10000,
  });

session.pingHost('8.8.8.8', function(err, target, sent, received) {
  var ms = err ? 0 : (received - sent);
  data = '/ping?op=' + op + '&ping=' + ms + '&t=' + timestamp;
  _logger(data);
  session.close();
});
```

And it triggered the error way sooner than expected.

This is the block of code in `raw-socket` that's outputting the error:

```
Socket.prototype.onRecvReady = function () {
	var me = this;
	var req = this.requests.shift ();
	try {
		this.wrap.recv (this.buffer, function (buffer, bytes, source) {
			var newBuffer = buffer.slice (0, bytes);
			me.emit ("message", newBuffer, source);
		});
	} catch (error) {
		me.emit ("error", error);
	}
}
```

I've looked into the implementation of the code below it and on error event instead of emitting the error, it's doing this `req.afterCallback.call` function which I assume would retry after some time.

```
Socket.prototype.onSendReady = function () {
	if (this.requests.length > 0) {
		var me = this;
		var req = this.requests.shift ();
		try {
			if (req.beforeCallback)
				req.beforeCallback ();
			this.wrap.send (req.buffer, req.offset, req.length,
					req.address, function (bytes) {
				req.afterCallback.call (me, null, bytes);
			});
		} catch (error) {
			req.afterCallback.call (me, error, 0);
		}
	} else {
		if (! this.sendPaused)
			this.pauseSend ();
	}
}
```

**Comment by stephenwvickers** [comment]
Can you run your process under strace (or similar), and send me the resulting file.  For example:

```shell
strace -f -ff -s 1024 node test-script.js > test-script.strace 2>&1
```

Once it quits, send the resulting output file.
