### ISSUE TITLE
Cannot install on Debian

### ISSUE THREAD

**Issue by OverByThere** [stephenwvickers/node-raw-socket#28]
Log:
```
root@svrmon:/var/www/html# mkdir raw
root@svrmon:/var/www/html# cd raw
root@svrmon:/var/www/html/raw# npm install raw-socket
/
> raw-socket@1.5.1 install /var/www/html/raw/node_modules/raw-socket
> node-gyp rebuild

make: Entering directory '/var/www/html/raw/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../src/raw.h:23:0,
                 from ../src/raw.cc:6:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::Send(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:662:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (args[3]);
   ^
../src/raw.cc:663:44: error: ‘address’ was not declared in this scope
   struct sockaddr_in6 addr = uv_ip6_addr (*address, 0);
                                            ^
../src/raw.cc:673:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (info[3]);
   ^
../src/raw.cc:674:43: error: ‘address’ was not declared in this scope
   struct sockaddr_in addr = uv_ip4_addr (*address, 0);
                                           ^
raw.target.mk:84: recipe for target 'Release/obj.target/raw/src/raw.o' failed
make: *** [Release/obj.target/raw/src/raw.o] Error 1
make: Leaving directory '/var/www/html/raw/node_modules/raw-socket/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/html/raw/node_modules/raw-socket
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! raw-socket@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.5.1 install script.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "raw-socket"
npm ERR! cwd /var/www/html/raw
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/raw/npm-debug.log
npm ERR! not ok code 0
```

I have installed nodejs-legacy, but as you can see above it does use nodejs to run install

**Comment by stephenwvickers** [comment]
Hi,

The latest versions of raw-socket are not tested or supported on Node.js 0.10.29.  You will need to upgrade to a later version, or you could try raw-socket version 1.2.2.

Note however, that a bug was fixed 1.4.0 which you may run into:

Add-on module crashes when emitting close events during garbage collection of a wrapped object

Steve
