### ISSUE TITLE
app called in rc.local

### ISSUE THREAD

**Issue by alexmarco1** [stephenwvickers/node-raw-socket#40]
I have a nodejs application that should start when I turn on the machine (I'm using Linux Ubuntu 16.04 so I put it in the rc.local). my application uses the raw-socket package.

Since my application cannot run as root, in the rc.local, I set:

sudo -u myuser node myapp.js &
when my application calls "new raw-socket", I got an error:

Operation not permitted.
I tried different methods such as "setcap" but they don't work for me.

Furthermore, if i try to run my app after the operating system is loaded, the app works perfectly without any problem....

should I have to add something in the rc.local....did I miss something?

**Comment by alexmarco1** [comment]
UPGRADE: I noticed that if I run the rc.local after the machine is completely loaded, I obtain the same result (it does not work). for this reason, I think the problem is related to the execution usign sudo -u.

**Comment by somec** [comment]
Did you run setcap on the node binary?

This works for me, on Fedora: 

> setcap cap_net_raw+ep /path/to/node-binary

**Comment by alexmarco1** [comment]
hi somec, yes but it does not work. As I said, running the app from console with my user it works perfectly...the problem is if I run it automatically in the rc.local.

**Comment by stephenwvickers** [comment]
Hi @alexmarco1 

So, out of the box I get:

```
$ node example/ping.js 8.8.8.8 1 10000
/home/stephen/projects/node-raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
                    ^

Error: Operation not permitted
    at new Socket (/home/stephen/projects/node-raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/stephen/projects/node-raw-socket/index.js:202:9)
    at Object.<anonymous> (/home/stephen/projects/node-raw-socket/example/ping.js:17:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
```

But, if I run:

```
sudo setcap cap_net_raw+ep /usr/local/bin/node
```

It then works:

```
[stephen@localhost node-raw-socket]$ node example/ping.js 8.8.8.8 1 10000
sent 40 bytes to 8.8.8.8
received 60 bytes from 8.8.8.8
data: 4500003cba3600003901f50008080808c0a801d200004b5200010a096162636465666768696a6b6c6d6e6f7071727374757677616263646566676869
^C
```

I am not sure what could be the problem in your environment.

Steve
