### ISSUE TITLE
can not compile (different node version)

### ISSUE THREAD

**Issue by ifElser** [stephenwvickers/node-raw-socket#42]
Hi
I am stuck with that problem:
```bash
[2018.03.30 11:01:42] elser@evm ~/node/projects/lab
$ sudo node ping 192.168.0.1 3 500
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/elser/node/projects/lab/node_modules/raw-socket/build/Release/raw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/elser/node/projects/lab/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

```

Full actions sequence can be viewed [here](https://pastebin.com/AgSxnnnS)

**Comment by somec** [comment]
Hi ifElser,

When this has happened to me I have resolved it successfully by deleting the node_modules folder and then run `npm install` to reinstall every module.

**Comment by ifElser** [comment]
Hi, somec,
Its don`t help me:
```bash
[2018.03.30 14:27:42] elser@evm ~/node/projects/lab
$ npm i nan
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN lab@1.0.0 No description
npm WARN lab@1.0.0 No repository field.

+ nan@2.10.0
added 1 package in 6.209s

[2018.03.30 14:28:06] elser@evm ~/node/projects/lab
$ npm i raw-socket

> raw-socket@1.5.2 install /home/elser/node/projects/lab/node_modules/raw-socket
> node-gyp rebuild

make: Вход в каталог `/home/elser/node/projects/lab/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/raw.h:23,
                 from ../src/raw.cc:6:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/elser/.node-gyp/9.10.0/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Выход из каталога `/home/elser/node/projects/lab/node_modules/raw-socket/build'
npm WARN lab@1.0.0 No description
npm WARN lab@1.0.0 No repository field.

+ raw-socket@1.5.2
added 2 packages in 23.404s

[2018.03.30 14:28:48] elser@evm ~/node/projects/lab
$ sed 's|require ("../")|require ("raw-socket")|' node_modules/raw-socket/example/ping.js > ./ping.js

[2018.03.30 14:28:57] elser@evm ~/node/projects/lab
$ sudo node ping 192.168.0.1 3 500
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/elser/node/projects/lab/node_modules/raw-socket/build/Release/raw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/elser/node/projects/lab/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

[2018.03.30 14:29:07] elser@evm ~/node/projects/lab
$ node ping 192.168.0.1 3 500
/home/elser/node/projects/lab/node_modules/raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
                    ^

Error: Operation not permitted
    at new Socket (/home/elser/node/projects/lab/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/elser/node/projects/lab/node_modules/raw-socket/index.js:202:9)
    at Object.<anonymous> (/home/elser/node/projects/lab/ping.js:17:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
```

**Comment by ifElser** [comment]
Thanks, @stephenwvickers, this is so;ve problem
Just by switching nvm default version for root
