### ISSUE TITLE
Error when building on System i (AS400)

### ISSUE THREAD

**Issue by crxo1** [stephenwvickers/node-raw-socket#44]
Hello,

node-gyp fails when trying to build on an IBM system i. Here is my error log:

```
bash-4.3# npm install raw-socket

> raw-socket@1.5.2 install /node/node_modules/raw-socket
> node-gyp rebuild

gmake: Entering directory '/node/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
g++: error trying to exec 'cc1plus': execvp: No such file or directory
raw.target.mk:91: recipe for target 'Release/obj.target/raw/src/raw.o' failed
gmake: *** [Release/obj.target/raw/src/raw.o] Error 1
gmake: Leaving directory '/node/node_modules/raw-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/QOpenSys/QIBM/ProdData/OPS/Node6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System OS400 3
gyp ERR! command "/QOpenSys/QIBM/ProdData/OPS/Node6/bin/node" "/QOpenSys/QIBM/ProdData/OPS/Node6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node/node_modules/raw-socket
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm ERR! OS400 3
npm ERR! argv "/QOpenSys/QIBM/ProdData/OPS/Node6/bin/node" "/QOpenSys/QIBM/ProdData/OPS/Node6/bin/npm" "install" "raw-socket"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.5.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /node/ping/npm-debug.log
```

**Comment by somec** [comment]
> g++: error trying to exec 'cc1plus': execvp: No such file or directory

It looks like it can't find a compiler for c++.

**Comment by stephenwvickers** [comment]
I agree with @somec, it looks like it can't find a compiler.

**Comment by crxo1** [comment]
Hello, thanks for your feedback. I've updated to a newer version of node but now i get an other error.

```
bash-4.4# npm install raw-socket

> raw-socket@1.5.2 install /node/node_modules/raw-socket
> node-gyp rebuild

gmake: Entering directory '/node/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from /QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/stl_algo.h:66:0,
                 from /QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/algorithm:62,
                 from ../node_modules/nan/nan.h:50,
                 from ../src/raw.h:23,
                 from ../src/raw.cc:6:
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:63:49: error: 'std::is_integral<_Tp>::value' is not a type
       static_assert(std::is_integral<_IntType>::value,
                                                 ^~~~~
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:64:7: error: expected identifier before string constant
       "template argument not an integral type");
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:64:7: error: expected ',' or '...' before string constant
gmake: *** [raw.target.mk:94: Release/obj.target/raw/src/raw.o] Error 1
gmake: Leaving directory '/node/node_modules/raw-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System OS400 7.3
gyp ERR! command "/QOpenSys/pkgs/lib/nodejs8/bin/node" "/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node/node_modules/raw-socket
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/QSECOFR/.npm/_logs/2018-04-23T07_28_24_620Z-debug.log
```

**Comment by stephenwvickers** [comment]
Hi @crxo1, while I am keen to help I don't have an IBM system to hand to support you :(

Version 1.5.2 of raw-socket compiles and works fine on Node.js 8.10.0 on 64bit intel running CentOS 7, so I am sure the issue is platform specific, e.g. these seem very platform specific to me:

```
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:63:49: error: 'std::is_integral<_Tp>::value' is not a type
       static_assert(std::is_integral<_IntType>::value,
                                                 ^~~~~
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:64:7: error: expected identifier before string constant
       "template argument not an integral type");
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/QOpenSys/pkgs/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/uniform_int_dist.h:64:7: error: expected ',' or '...' before string constant
````

I am not sure how I can help you?
